#! /bin/bash

printf "This will set the bash prompt, do you wish to continue (y* to confirm?) " 
read answer

# this line is confusing
# ${answer#[Yy]} is a function that strips prefix
# we're comparing the var string to the var string after any Y/y prefix strip
if [ $answer = "${answer#[Yy]}" ]; then
	exit 1
fi

# sets the user home to the calling user, not root
USER_HOME=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)

if [ -f ~/.bashrc ]; then
    echo "PS1=\"%F{14}%n@%m%f %F{12}%D{%d/%m/%y %H:%M:%S}%f %F{13}%1~%f %B%#%b\"" >> $USER_HOME/.bashrc
	echo "wrote to ~/.bashrc"
	tput bel
else
    echo ".bashrc not found or permissions issue"
	if [ -f ~/.bash_profile ]; then
		echo "PS1=\"%F{14}%n@%m%f %F{12}%D{%d/%m/%y %H:%M:%S}%f %F{13}%1~%f %B%#%b\""  >> $USER_HOME/.bash_profile
		echo "wrote to ~/.bash_profile"
		tput bel
	else
		echo ".bash_profile not found or permissions issue"
		if [ -f ~/.profile ]; then
			echo "PS1=\"%F{14}%n@%m%f %F{12}%D{%d/%m/%y %H:%M:%S}%f %F{13}%1~%f %B%#%b\""  >> $USER_HOME/.profile
			echo "wrote to ~/.profile"
			tput bel
		else
			echo ".profile not found or permissions issue"
			exit 2
		fi
	fi
fi
